<?php

use Drupal\node\NodeInterface;


/**
 * @file
 * Contains az_contact.module.
 */



function az_contact_entity_insert(NodeInferface $entity) {
  $type = $entity->getEntityTypeId();
  if ($entity->getEntityTypeId() == 'contact_message') {
    $wow = 6;
    // Submit it like we talked
  }
}

function az_contact_node_insert(NodeInterface $node) {
  $type = $node->getEntityTypeId();
  if ($node->getEntityTypeId() == 'contact_message') {
    $wow = 6;
    // Submit it like we talked
  }
}

function az_contact_node_update(NodeInterface $node) {
  $type = $node->getEntityTypeId();
  if ($node->getEntityTypeID() == 'contact_message') {
    $wow = 6;
    // Submit it like we talked
  }
}


